name: Build and Deploy to aliyun

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16 "
      - name: Install pnpm
        run: npm i pnpm -g
      - name: Install dependencies
        run: pnpm i
      - name: Run build task
        run: yarn build
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          CI: true
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: yihua
          REMOTE_HOST: "121.40.19.111"
          REMOTE_USER: root
          TARGET: /usr/share/nginx/html
